### ISSUE TITLE
The newest version (1.0.1) does not work when setting browser zoom

### ISSUE THREAD

**Issue by codelab2006** [daybrush/overlap-area#1]
![overlap-area 1 0 1](https://user-images.githubusercontent.com/39729306/174518938-785df565-e000-4cd0-b3a8-b696ddbae324.png)

**Comment by daybrush** [comment]
@codelab2006 

Thank you :) 1.1.0 is released. And demo is fixed.

**Comment by codelab2006** [comment]
Thank you :-)
